#!/usr/bin/env bash
set -eufo pipefail
cd "$(dirname "$0")/.."

if [[ $# == 0 ]]; then
    echo "Usage: $0 <some command> [<some flags>]}" >/dev/stderr
    exit 1
fi

bin_name="$1"
full_command=("$@")

cat <<- 'EOF' | sed "s/%command%/${full_command[*]}/g" > "$bin_name"
#!/bin/bash
# Command is autogenerated by ./dev/generate-command.sh
set -eufo pipefail
cur_dir="$(cd "$(dirname "$0")" && pwd)"
arch="$(uname -m)"
bin="$cur_dir/bin/$arch/busybox"
if [[ ! -f "$bin" ]]; then
    echo "Unknown arch: $arch" >/dev/stderr
    exit 1
fi
"$bin" %command% "$@"
EOF

chmod +x "$bin_name"
